In [17]:
import pandas as pd

In [18]:
import matplotlib.pyplot as plt

In [30]:
data = pd.read_clipboard(header = None)
data.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [27]:
#data = pd.read_csv("Bioinformatics.csv")

,0,1,2,3,4,5,6,7,8
0,QIA,Qiagen NV,EUR,1.000000,25%,Diagnostic,NaN,NaN,40.155
1,SAN,Sanofi SA,EUR,1.000000,25%,Pharma,NaN,NaN,86.450
2,TMO,Thermo Fisher Scientific Inc,USD,1.086055,25%,Device,NaN,0.0,575.390
3,VEEV,Veeva Systems Inc,USD,1.086055,25%,SaaS,NaN,0.0,223.610
4,LONN,Lonza Group AG,CHF,0.961794,0%,Chemical,NaN,0.0,461.800
5,UTHR,United Therapeutics Corporation,USD,1.086055,0%,Device,NaN,0.0,227.250
8,CPRX,Catalyst Pharmaceuticals Inc,USD,1.086055,0%,R&D,NaN,0.0,16.920
9,EVT,Evotec SE,EUR,1.000000,0%,Precision medicine,NaN,NaN,13.470
10,VRTX,Vertex Pharmaceuticals Incorporated,USD,1.086055,0%,Pharma,NaN,0.0,427.860
11,CTKB,Cytek Biosciences Inc,USD,1.086055,0%,Pharma,NaN,0.0,8.070

In [32]:
data.columns = ['ticker', 'name', 'currency', 'rate_currency', 'percent', 'sector', 'c1', 'c2', 'price']

In [33]:
data

,ticker,name,currency,rate_currency,percent,sector,c1,c2,price
0,QIA,Qiagen NV,EUR,1.000000,25%,Diagnostic,NaN,NaN,40.155
1,SAN,Sanofi SA,EUR,1.000000,25%,Pharma,NaN,NaN,86.450
2,TMO,Thermo Fisher Scientific Inc,USD,1.086055,25%,Device,NaN,0.0,575.390
3,VEEV,Veeva Systems Inc,USD,1.086055,25%,SaaS,NaN,0.0,223.610
4,LONN,Lonza Group AG,CHF,0.961794,0%,Chemical,NaN,0.0,461.800
5,UTHR,United Therapeutics Corporation,USD,1.086055,0%,Device,NaN,0.0,227.250
8,CPRX,Catalyst Pharmaceuticals Inc,USD,1.086055,0%,R&D,NaN,0.0,16.920
9,EVT,Evotec SE,EUR,1.000000,0%,Precision medicine,NaN,NaN,13.470
10,VRTX,Vertex Pharmaceuticals Incorporated,USD,1.086055,0%,Pharma,NaN,0.0,427.860
11,CTKB,Cytek Biosciences Inc,USD,1.086055,0%,Pharma,NaN,0.0,8.070

In [36]:
data.drop(['percent', 'c1', 'c2'], axis = 1, inplace=True)
data

,ticker,name,currency,rate_currency,sector,price
0,QIA,Qiagen NV,EUR,1.000000,Diagnostic,40.155
1,SAN,Sanofi SA,EUR,1.000000,Pharma,86.450
2,TMO,Thermo Fisher Scientific Inc,USD,1.086055,Device,575.390
3,VEEV,Veeva Systems Inc,USD,1.086055,SaaS,223.610
4,LONN,Lonza Group AG,CHF,0.961794,Chemical,461.800
5,UTHR,United Therapeutics Corporation,USD,1.086055,Device,227.250
8,CPRX,Catalyst Pharmaceuticals Inc,USD,1.086055,R&D,16.920
9,EVT,Evotec SE,EUR,1.000000,Precision medicine,13.470
10,VRTX,Vertex Pharmaceuticals Incorporated,USD,1.086055,Pharma,427.860
11,CTKB,Cytek Biosciences Inc,USD,1.086055,Pharma,8.070

In [37]:
data.to_csv("Bioinformatics.csv", index = False)

In [38]:
data.sort_values("price")

,ticker,name,currency,rate_currency,sector,price
11,CTKB,Cytek Biosciences Inc,USD,1.086055,Pharma,8.070
9,EVT,Evotec SE,EUR,1.000000,Precision medicine,13.470
8,CPRX,Catalyst Pharmaceuticals Inc,USD,1.086055,R&D,16.920
0,QIA,Qiagen NV,EUR,1.000000,Diagnostic,40.155
1,SAN,Sanofi SA,EUR,1.000000,Pharma,86.450
3,VEEV,Veeva Systems Inc,USD,1.086055,SaaS,223.610
5,UTHR,United Therapeutics Corporation,USD,1.086055,Device,227.250
10,VRTX,Vertex Pharmaceuticals Incorporated,USD,1.086055,Pharma,427.860
4,LONN,Lonza Group AG,CHF,0.961794,Chemical,461.800
2,TMO,Thermo Fisher Scientific Inc,USD,1.086055,Device,575.390